CREATE TABLE "NORTHWINDDB"."STAGE_SCHEMA"."ORDERS" (
    "ORDERID" NUMBER (38,0) NOT NULL,
    "CUSTOMERID" VARCHAR (50) NOT NULL,
    "EMPLOYEEID" NUMBER (38,0) NOT NULL,
    "ORDERDATE" DATE, 
    "REQUIREDDATE" DATE,  
    "SHIPPEDDATE" DATE,
    "SHIPVIA" INT,
    "FREIGHT" NUMBER (38,0),
    "SHIPNAME" VARCHAR (50),
    "SHIPADDRESS" VARCHAR (50),
    "SHIPCITY" VARCHAR (50),
    "SHIPREGION" VARCHAR (50),
    "SHIPPOSTALCODE" VARCHAR (50),
    "SHIPCOUNTRY" VARCHAR (50)
);


CREATE TABLE "NORTHWINDDB"."STAGE_SCHEMA"."ORDERDETAILS" (
    "ORDERID" NUMBER (38,0) NOT NULL,
    "PRODUCTID" NUMBER (38,0) NOT NULL,
    "UNITPRICE" NUMBER (38,0),
    "QUANTITY" NUMBER (38,0),
    "DISCOUNT" FLOAT
);
